"""
core/gitops/bridge.py — Autonomous GitOps Bridge
==================================================
Enables Jarvis to manage its own source code lifecycle: create feature
branches, commit generated artefacts, push to GitHub, and open Pull
Requests — all programmatically, without human intervention.

SECURITY CONTRACT
-----------------
  - GITHUB_TOKEN is fetched exclusively from the SecretsVault (ADR-003).
    It is NEVER read from os.environ directly or hardcoded.
  - All shell commands are issued via subprocess with a fixed argument list
    (no shell=True, no string interpolation into commands) — immune to
    command injection from LLM-generated branch names or commit messages.
  - Branch names and commit messages are sanitised before use.

FLOW IN SOFTWARE FACTORY
------------------------
  Sandbox PASS + Guardian SEAL
          │
          ▼
  GitOpsBridge.create_feature_branch(f"feat/jarvis-auto-{run_id}")
          │
          ▼
  GitOpsBridge.commit_changes("feat: auto-generated <description>")
          │
          ▼
  GitOpsBridge.push_and_pr(title, body)  → GitHub PR opened
          │
          ▼
  CI pipeline (jarvis-ci.yml) runs Zero-Trust + DLP + Guardrail tests
          │
          ▼
  Human reviews PR → merge or close

Usage:
    from core.gitops.bridge import get_gitops_bridge

    bridge = get_gitops_bridge()
    bridge.create_feature_branch("feat/my-feature")
    bridge.commit_changes("feat: add fibonacci module")
    bridge.push_and_pr("Add fibonacci module", "Auto-generated by Jarvis Factory")
"""

import logging
import re
import subprocess
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ── Config ─────────────────────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).resolve().parents[2]   # C:\Jarvis
_DEFAULT_REMOTE = "origin"
_DEFAULT_BASE_BRANCH = "main"
_GH_BIN = "gh"
_GIT_BIN = "git"

# Allowlist for branch name characters (git-safe subset)
_BRANCH_SAFE = re.compile(r"[^a-zA-Z0-9._/\-]")
# Commit message: strip shell-sensitive characters
_MSG_SAFE = re.compile(r"[\"'`$\\]")


# ── Result type ────────────────────────────────────────────────────────────────

@dataclass
class GitOpsResult:
    success: bool
    stdout: str = ""
    stderr: str = ""
    pr_url: Optional[str] = None

    def __str__(self) -> str:
        if self.success:
            return f"OK — {self.stdout.strip()[:120]}"
        return f"FAIL — {self.stderr.strip()[:200]}"


# ── Helpers ────────────────────────────────────────────────────────────────────

def _sanitise_branch(name: str) -> str:
    """Replace unsafe chars with '-', collapse duplicates, strip leading dots."""
    safe = _BRANCH_SAFE.sub("-", name)
    safe = re.sub(r"-{2,}", "-", safe).strip("-.")
    return safe[:100]


def _sanitise_message(msg: str) -> str:
    """Strip characters that could break git commit -m quoting."""
    return _MSG_SAFE.sub("", msg)[:200]


def _run(cmd: list[str], cwd: Path, env_extra: Optional[dict] = None) -> GitOpsResult:
    """
    Execute a command as a fixed argument list (no shell=True).
    Returns GitOpsResult with stdout/stderr captured.
    """
    import os
    env = os.environ.copy()
    if env_extra:
        env.update(env_extra)

    logger.debug("[GITOPS] Running: %s", " ".join(cmd))
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=60,
            env=env,
        )
        result = GitOpsResult(
            success=proc.returncode == 0,
            stdout=proc.stdout,
            stderr=proc.stderr,
        )
        if not result.success:
            logger.error("[GITOPS] Command failed (exit %d): %s\n%s",
                         proc.returncode, " ".join(cmd), proc.stderr[:300])
        return result
    except subprocess.TimeoutExpired:
        logger.error("[GITOPS] Timeout: %s", " ".join(cmd))
        return GitOpsResult(success=False, stderr="Timeout after 60s")
    except FileNotFoundError:
        logger.error("[GITOPS] Binary not found: %s", cmd[0])
        return GitOpsResult(success=False, stderr=f"{cmd[0]!r} not found in PATH")


# ── GitOpsBridge ──────────────────────────────────────────────────────────────

class GitOpsBridge:
    """
    Programmatic Git + GitHub CLI wrapper.
    All credentials fetched from SecretsVault — never from env directly.
    """

    def __init__(self, repo_root: Path = _REPO_ROOT) -> None:
        self._root = repo_root
        self._token: Optional[str] = None
        self._current_branch: Optional[str] = None
        logger.info("[GITOPS] Bridge initialised for repo: %s", repo_root)

    # ── Credential resolution ─────────────────────────────────────────────

    def _get_token(self) -> str:
        """Fetch GITHUB_TOKEN from the vault (lazy, cached for lifetime of bridge)."""
        if self._token:
            return self._token
        try:
            from core.security.vault import get_secrets_manager
            vault = get_secrets_manager()
            token = vault.require_secret("GITHUB_TOKEN")
            self._token = token
            logger.debug("[GITOPS] GITHUB_TOKEN resolved from vault.")
            return token
        except Exception as exc:
            raise RuntimeError(
                f"[GITOPS] Could not fetch GITHUB_TOKEN from vault: {exc}. "
                "Add GITHUB_TOKEN to your .env or secret store."
            ) from exc

    # ── Branch management ─────────────────────────────────────────────────

    def create_feature_branch(self, branch_name: str) -> GitOpsResult:
        """
        Create and checkout a new branch from the current HEAD.

        Args:
            branch_name: Desired branch name. Will be sanitised automatically.
        """
        safe_name = _sanitise_branch(branch_name)
        logger.info("[GITOPS] Creating branch: %s", safe_name)
        result = _run([_GIT_BIN, "checkout", "-b", safe_name], cwd=self._root)
        if result.success:
            self._current_branch = safe_name
        return result

    def checkout_branch(self, branch_name: str) -> GitOpsResult:
        """Checkout an existing branch."""
        safe_name = _sanitise_branch(branch_name)
        result = _run([_GIT_BIN, "checkout", safe_name], cwd=self._root)
        if result.success:
            self._current_branch = safe_name
        return result

    # ── Commit ────────────────────────────────────────────────────────────

    def stage_files(self, paths: Optional[list[str]] = None) -> GitOpsResult:
        """
        Stage specific files or all changes.

        Prefer explicit paths over `git add .` to avoid accidentally
        staging secrets or large binaries.
        """
        if paths:
            cmd = [_GIT_BIN, "add", "--"] + [str(p) for p in paths]
        else:
            cmd = [_GIT_BIN, "add", "--all"]
        return _run(cmd, cwd=self._root)

    def commit_changes(
        self,
        message: str,
        paths: Optional[list[str]] = None,
        author_name: str = "Jarvis v6.0",
        author_email: str = "jarvis@autonomous.local",
    ) -> GitOpsResult:
        """
        Stage `paths` (or all changes) and create a signed commit.

        Args:
            message: Commit message — sanitised for shell safety.
            paths:   Explicit file paths to stage. None = stage all.
            author_name / author_email: Git author identity for the commit.
        """
        safe_msg = _sanitise_message(message)

        stage = self.stage_files(paths)
        if not stage.success:
            return stage

        result = _run(
            [
                _GIT_BIN, "commit",
                "--author", f"{author_name} <{author_email}>",
                "-m", safe_msg,
            ],
            cwd=self._root,
        )
        return result

    # ── Push & PR ─────────────────────────────────────────────────────────

    def push_branch(self, remote: str = _DEFAULT_REMOTE) -> GitOpsResult:
        """Push the current branch to `remote`, setting upstream tracking."""
        branch = self._current_branch or "HEAD"
        token = self._get_token()
        return _run(
            [_GIT_BIN, "push", "--set-upstream", remote, branch],
            cwd=self._root,
            env_extra={"GIT_ASKPASS": "echo", "GITHUB_TOKEN": token},
        )

    def push_and_pr(
        self,
        title: str,
        body: str,
        base_branch: str = _DEFAULT_BASE_BRANCH,
        draft: bool = True,
    ) -> GitOpsResult:
        """
        Push the current branch and open a GitHub Pull Request.

        Args:
            title:        PR title (sanitised).
            body:         PR description (Markdown).
            base_branch:  Target branch for the merge (default: main).
            draft:        Open as draft PR (recommended for auto-generated code).

        Returns:
            GitOpsResult with pr_url populated on success.
        """
        push = self.push_branch()
        if not push.success:
            return push

        token = self._get_token()
        safe_title = _sanitise_message(title)

        cmd = [
            _GH_BIN, "pr", "create",
            "--title", safe_title,
            "--body",  body,
            "--base",  base_branch,
        ]
        if draft:
            cmd.append("--draft")

        result = _run(cmd, cwd=self._root, env_extra={"GITHUB_TOKEN": token})

        if result.success:
            # gh pr create outputs the PR URL on stdout
            result.pr_url = result.stdout.strip().splitlines()[-1]
            logger.info("[GITOPS] PR opened: %s", result.pr_url)

        return result

    # ── Convenience: full factory handover ───────────────────────────────

    def factory_handover(
        self,
        run_id: str,
        description: str,
        files_to_commit: list[str],
        pr_body: str,
    ) -> GitOpsResult:
        """
        Single-call convenience method for software_factory.py integration.

        1. Creates feat/jarvis-auto-<run_id> branch.
        2. Stages specific files only (no accidental secret commits).
        3. Commits with a structured message.
        4. Opens a draft PR for human review.
        """
        branch = f"feat/jarvis-auto-{run_id}"
        r = self.create_feature_branch(branch)
        if not r.success:
            return r

        commit_msg = f"feat(auto): {description[:100]}"
        r = self.commit_changes(message=commit_msg, paths=files_to_commit)
        if not r.success:
            return r

        pr_title = f"[Jarvis Auto] {description[:70]}"
        return self.push_and_pr(title=pr_title, body=pr_body, draft=True)


# ── Singleton ──────────────────────────────────────────────────────────────────

_instance: Optional[GitOpsBridge] = None


def get_gitops_bridge(repo_root: Path = _REPO_ROOT) -> GitOpsBridge:
    global _instance
    if _instance is None:
        _instance = GitOpsBridge(repo_root=repo_root)
    return _instance
